version: "3.9"
services:
  llama1:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 8
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - CUDA_DEVICE_ORDER=PCI_BUS_ID
  llama2:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 8
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=1
      - CUDA_DEVICE_ORDER=PCI_BUS_ID
  llama3:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 8
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=2
      - CUDA_DEVICE_ORDER=PCI_BUS_ID
  llama4:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 8
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=3
      - CUDA_DEVICE_ORDER=PCI_BUS_ID
  llama5:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 8
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=4
      - CUDA_DEVICE_ORDER=PCI_BUS_ID
  llama6:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 8
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=5
      - CUDA_DEVICE_ORDER=PCI_BUS_ID
  llama7:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 8
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=6
      - CUDA_DEVICE_ORDER=PCI_BUS_ID
  llama8:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 8
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=7
      - CUDA_DEVICE_ORDER=PCI_BUS_ID